<?php

/**
 * @file
 * Various hook implementations.
 */

/**
 * Implements hook_menu().
 */
function usc_mirc_reporting_menu() {
  $items = array();

  $items['admin/reports/usc_mirc'] = array(
    'title' => 'USC MIRC Assets',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('usc_mirc_reporting_form'),
    'access callback' => 'usc_mirc_reporting_access',
    'file' => 'includes/report.form.inc',
  );
  $items['admin/reports/usc_mirc/csv'] = array(
    'title' => 'USC MIRC CSV Download',
    'page callback' => 'usc_mirc_reporting_build_csv_structure',
    'delivery callback' => 'usc_mirc_reporting_deliver_csv',
    'access callback' => 'usc_mirc_reporting_csv_access',
    'file' => 'includes/report.csv.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function usc_mirc_reporting_theme($existing, $type, $theme, $path) {
  $items = array();

  $items['usc_mirc_reporting_report_table'] = array(
    'variables' => $existing['table']['variables'] + array(
      'report_structure' => array(),
    ),
    'file' => 'theme/theme.inc',
    'function' => 'theme_table',
  );

  return $items;
}

/**
 * Access callback for the CSV output callback.
 */
function usc_mirc_reporting_csv_access() {
  return usc_mirc_reporting_access() && variable_get('usc_mirc_reporting_report', FALSE);
}

/**
 * Determine whether the current user has access to the reports section.
 */
function usc_mirc_reporting_access() {
  global $user;
  $allowed_roles = array('Creator', 'Editor', 'Submitter', 'administrator');
  return count(array_intersect($user->roles, $allowed_roles)) > 0;
}
